# Generated by Django 6.1.1 on 2026-10-06 11:42

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_member', '0004_rename_legacy_preference_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonGroup',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True, null=True)),
                ('secret_ciphertext', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('private', 'Prive')], default='open', max_length=32)),
            ],
            options={
                'db_table': 'common"."g_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommonGroupJoinRequest',
            fields=[
                ('pk', models.CompositePrimaryKey('group_id', 'member_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('member_id', models.UUIDField()),
            ],
            options={
                'db_table': 'common"."g_group_user_ask_to_join',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommonGroupTag',
            fields=[
                ('gt_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'common"."group_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommonGroupUser',
            fields=[
                ('pk', models.CompositePrimaryKey('group_id', 'member_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('member_id', models.UUIDField()),
                ('is_group_admin', models.BooleanField(default=False)),
                ('am_access', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'common"."g_group_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('gg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('celebration_retention_months', models.PositiveSmallIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'am"."g_group',
                'constraints': [models.CheckConstraint(condition=models.Q(('celebration_retention_months__gte', 1), ('celebration_retention_months__lte', 24)), name='g_group_retention_months_valid')],
            },
        ),
        migrations.CreateModel(
            name='AmMemberTitle',
            fields=[
                ('gamt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(db_column='gg_id', on_delete=django.db.models.deletion.CASCADE, related_name='am_member_titles', to='app_group.group')),
            ],
            options={
                'db_table': 'am"."g_am_member_title',
                'ordering': ['position', 'gamt_id'],
            },
        ),
        migrations.CreateModel(
            name='GroupFunction',
            fields=[
                ('gf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_edit_celebration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='gg_id', on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='app_group.group')),
            ],
            options={
                'db_table': 'am"."g_function',
                'ordering': ['position', 'gf_id'],
            },
        ),
        migrations.CreateModel(
            name='GroupLocation',
            fields=[
                ('gl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='gg_id', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app_group.group')),
            ],
            options={
                'db_table': 'am"."g_location',
                'ordering': ['position', 'gl_id'],
            },
        ),
        migrations.CreateModel(
            name='CelebrationRule',
            fields=[
                ('gcr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('time', models.TimeField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_gcr_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_rules', to='app_group.celebrationrule')),
                ('group', models.ForeignKey(db_column='gg_id', on_delete=django.db.models.deletion.CASCADE, related_name='celebration_rules', to='app_group.group')),
                ('location', models.ForeignKey(db_column='gl_id', on_delete=django.db.models.deletion.PROTECT, related_name='celebration_rules', to='app_group.grouplocation')),
            ],
            options={
                'db_table': 'am"."g_celebration_rule',
                'ordering': ['position', 'gcr_id'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('ggm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_kind', models.CharField(choices=[('account', 'Compte'), ('am', 'Membre AM')], max_length=16)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='gg_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app_group.group')),
                ('member', models.ForeignKey(blank=True, db_column='mm_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='app_member.member')),
            ],
            options={
                'db_table': 'am"."g_group_member',
            },
        ),
        migrations.CreateModel(
            name='AmMemberRequest',
            fields=[
                ('gamr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('consent_token_hash', models.CharField(max_length=255)),
                ('consent_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('refused', 'Refusee'), ('expired', 'Expiree')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('refused_at', models.DateTimeField(blank=True, null=True)),
                ('display_hint', models.CharField(blank=True, max_length=255)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='gg_id', on_delete=django.db.models.deletion.CASCADE, related_name='am_member_requests', to='app_group.group')),
                ('requested_by', models.ForeignKey(blank=True, db_column='requested_by_ggm_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_am_members', to='app_group.groupmember')),
            ],
            options={
                'db_table': 'am"."g_am_member_request',
            },
        ),
        migrations.CreateModel(
            name='AmMember',
            fields=[
                ('gam_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('consented_at', models.DateTimeField()),
                ('consent_version', models.CharField(max_length=64)),
                ('consent_email_fingerprint', models.CharField(max_length=255)),
                ('withdrawal_secret_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.ForeignKey(blank=True, db_column='gamt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='am_members', to='app_group.ammembertitle')),
                ('group_member', models.OneToOneField(db_column='ggm_id', on_delete=django.db.models.deletion.CASCADE, related_name='am_profile', to='app_group.groupmember')),
            ],
            options={
                'db_table': 'am"."g_am_member',
            },
        ),
        migrations.CreateModel(
            name='GroupMemberFunction',
            fields=[
                ('ggmf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function', models.ForeignKey(db_column='gf_id', on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='app_group.groupfunction')),
                ('group_member', models.ForeignKey(db_column='ggm_id', on_delete=django.db.models.deletion.CASCADE, related_name='function_assignments', to='app_group.groupmember')),
            ],
            options={
                'db_table': 'am"."g_group_member_function',
            },
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('gr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='gg_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='app_group.group')),
            ],
            options={
                'db_table': 'am"."g_role',
                'ordering': ['position', 'gr_id'],
            },
        ),
        migrations.CreateModel(
            name='GroupMemberRole',
            fields=[
                ('ggmr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_member', models.ForeignKey(db_column='ggm_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='app_group.groupmember')),
                ('role', models.ForeignKey(db_column='gr_id', on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='app_group.grouprole')),
            ],
            options={
                'db_table': 'am"."g_group_member_role',
            },
        ),
        migrations.CreateModel(
            name='PlanningState',
            fields=[
                ('gps_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=32)),
                ('kind', models.CharField(choices=[('selection', 'Selection'), ('default', 'Defaut'), ('custom', 'Personnalise')], max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='gg_id', on_delete=django.db.models.deletion.CASCADE, related_name='planning_states', to='app_group.group')),
            ],
            options={
                'db_table': 'am"."g_planning_state',
                'ordering': ['position', 'gps_id'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('ss_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('song_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='gg_id', on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='app_group.group')),
            ],
            options={
                'db_table': 'am"."s_song',
            },
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('sst_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_tag', models.ForeignKey(db_column='gt_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='song_tags', to='app_group.commongrouptag')),
                ('song', models.ForeignKey(db_column='ss_id', on_delete=django.db.models.deletion.CASCADE, related_name='song_tags', to='app_group.song')),
            ],
            options={
                'db_table': 'am"."s_song_tag',
            },
        ),
        migrations.CreateModel(
            name='SpecialDateRule',
            fields=[
                ('gsdr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(max_length=32)),
                ('collision_mode', models.CharField(max_length=16)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exact_date', models.DateField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('occurrence', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='gg_id', on_delete=django.db.models.deletion.CASCADE, related_name='special_date_rules', to='app_group.group')),
            ],
            options={
                'db_table': 'am"."g_special_date_rule',
            },
        ),
        migrations.CreateModel(
            name='SpecialDateCelebration',
            fields=[
                ('gsdc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(db_column='gl_id', on_delete=django.db.models.deletion.PROTECT, related_name='special_date_celebrations', to='app_group.grouplocation')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_gsdc_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_celebrations', to='app_group.specialdatecelebration')),
                ('special_date_rule', models.ForeignKey(db_column='gsdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='celebrations', to='app_group.specialdaterule')),
            ],
            options={
                'db_table': 'am"."g_special_date_celebration',
                'ordering': ['position', 'gsdc_id'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('sv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verse_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(db_column='ss_id', on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='app_group.song')),
            ],
            options={
                'db_table': 'am"."s_verse',
            },
        ),
        migrations.CreateModel(
            name='SongTagVerse',
            fields=[
                ('sstv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('selected_by_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song_tag', models.ForeignKey(db_column='sst_id', on_delete=django.db.models.deletion.CASCADE, related_name='verse_selections', to='app_group.songtag')),
                ('verse', models.ForeignKey(db_column='sv_id', on_delete=django.db.models.deletion.CASCADE, related_name='tag_selections', to='app_group.verse')),
            ],
            options={
                'db_table': 'am"."s_song_tag_verse',
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('gar_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('am_access', 'Acces AM')], default='am_access', max_length=16)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('consent_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(db_column='mm_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='group_access_requests', to='app_member.member')),
                ('group', models.ForeignKey(db_column='gg_id', on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='app_group.group')),
            ],
            options={
                'db_table': 'am"."g_access_request',
                'constraints': [models.CheckConstraint(condition=models.Q(('request_type', 'am_access')), name='g_access_request_type_valid'), models.UniqueConstraint(fields=('group', 'member', 'request_type'), name='g_access_request_active_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='groupfunction',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('group'), name='g_function_group_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('member__isnull', False), ('member_kind', 'account')), models.Q(('member__isnull', True), ('member_kind', 'am')), _connector='OR'), name='g_group_member_kind_member_valid'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False), ('member_kind', 'account')), fields=('group', 'member'), name='g_group_member_account_unique'),
        ),
        migrations.AddConstraint(
            model_name='groupmemberfunction',
            constraint=models.UniqueConstraint(fields=('group_member', 'function'), name='g_group_member_function_unique'),
        ),
        migrations.AddConstraint(
            model_name='grouprole',
            constraint=models.UniqueConstraint(fields=('group', 'code'), name='g_role_group_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='groupmemberrole',
            constraint=models.UniqueConstraint(fields=('group_member', 'role'), name='g_group_member_role_unique'),
        ),
        migrations.AddConstraint(
            model_name='planningstate',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['selection', 'default', 'custom'])), name='g_planning_state_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='planningstate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('kind', 'selection')), fields=('group', 'kind'), name='g_planning_state_active_selection_unique'),
        ),
        migrations.AddConstraint(
            model_name='planningstate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('kind', 'default')), fields=('group', 'kind'), name='g_planning_state_active_default_unique'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('group', 'song_id'), name='s_song_group_song_unique'),
        ),
        migrations.AddConstraint(
            model_name='songtag',
            constraint=models.UniqueConstraint(fields=('song', 'group_tag'), name='s_song_tag_unique'),
        ),
        migrations.AddConstraint(
            model_name='specialdaterule',
            constraint=models.CheckConstraint(condition=models.Q(('rule_type__in', ['annual_fixed', 'one_off', 'nth_weekday'])), name='g_special_date_rule_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='specialdaterule',
            constraint=models.CheckConstraint(condition=models.Q(('collision_mode__in', ['add', 'replace'])), name='g_special_date_rule_collision_valid'),
        ),
        migrations.AddConstraint(
            model_name='verse',
            constraint=models.UniqueConstraint(fields=('song', 'verse_id'), name='s_verse_song_verse_unique'),
        ),
        migrations.AddConstraint(
            model_name='songtagverse',
            constraint=models.UniqueConstraint(fields=('song_tag', 'verse'), name='s_song_tag_verse_unique'),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE "am"."g_group"
            ADD CONSTRAINT "g_group_common_group_fk"
            FOREIGN KEY ("gg_id")
            REFERENCES "common"."g_groups" ("group_id")
            ON DELETE CASCADE;

            ALTER TABLE "am"."g_group_member"
            ADD CONSTRAINT "g_group_member_member_fk"
            FOREIGN KEY ("mm_id")
            REFERENCES "am"."m_member" ("mm_id")
            ON DELETE CASCADE;

            ALTER TABLE "am"."g_group_member"
            ADD CONSTRAINT "g_group_member_common_membership_fk"
            FOREIGN KEY ("gg_id", "mm_id")
            REFERENCES "common"."g_group_user" ("group_id", "member_id")
            ON DELETE CASCADE;

            ALTER TABLE "am"."g_access_request"
            ADD CONSTRAINT "g_access_request_member_fk"
            FOREIGN KEY ("mm_id")
            REFERENCES "am"."m_member" ("mm_id")
            ON DELETE CASCADE;

            ALTER TABLE "am"."g_access_request"
            ADD CONSTRAINT "g_access_request_common_membership_fk"
            FOREIGN KEY ("gg_id", "mm_id")
            REFERENCES "common"."g_group_user" ("group_id", "member_id")
            ON DELETE CASCADE;

            ALTER TABLE "am"."s_song"
            ADD CONSTRAINT "s_song_lss_song_fk"
            FOREIGN KEY ("song_id")
            REFERENCES "lss"."s_songs" ("song_id")
            ON DELETE CASCADE;

            ALTER TABLE "am"."s_verse"
            ADD CONSTRAINT "s_verse_lss_verse_fk"
            FOREIGN KEY ("verse_id")
            REFERENCES "lss"."s_verses" ("verse_id")
            ON DELETE CASCADE;

            """,
            reverse_sql="""
            ALTER TABLE "am"."s_verse"
            DROP CONSTRAINT IF EXISTS "s_verse_lss_verse_fk";

            ALTER TABLE "am"."s_song"
            DROP CONSTRAINT IF EXISTS "s_song_lss_song_fk";

            ALTER TABLE "am"."g_access_request"
            DROP CONSTRAINT IF EXISTS "g_access_request_common_membership_fk";

            ALTER TABLE "am"."g_access_request"
            DROP CONSTRAINT IF EXISTS "g_access_request_member_fk";

            ALTER TABLE "am"."g_group_member"
            DROP CONSTRAINT IF EXISTS "g_group_member_common_membership_fk";

            ALTER TABLE "am"."g_group_member"
            DROP CONSTRAINT IF EXISTS "g_group_member_member_fk";

            ALTER TABLE "am"."g_group"
            DROP CONSTRAINT IF EXISTS "g_group_common_group_fk";
            """,
        ),
    ]
